name: Check npm version

on:
  push:
    paths:
      - package.json
      - package-lock.json

jobs:
  check-version:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1

      - run: node -pe \"process.exit(require('./package.json').version !== require('./package-lock.json').version);\"
