name: Check version changed

on:
  pull_request:
    branches:
      - master
      - develop

env:
  DIST_TAG_MASTER: latest
  DIST_TAG_DEVELOP: next

jobs:
  check-version-changed:
    name: Check package.json version is updated
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Ensure package version updated
        run: |2
          set -ex

          incoming_version=$(node -pe "require('./package.json').version;")

          if [ ! -z "$(npm view xrange@$incoming_version version)" ]; then
            echo "This version ($incoming_version) is already published; please, update version by running 'npm version <version>'"
            exit 1
          fi
