name: Publish xrange

on:
  push:
    branches:
      - master
      - develop

env:
  DIST_TAG_MASTER: latest
  DIST_TAG_DEVELOP: next

jobs:
  publish-latest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - run: |2
          set -ex

          if [ "$GITHUB_REF" = "refs/heads/master" ]
          then
            dist_tag=$DIST_TAG_MASTER
          elif [ "$GITHUB_REF" = "refs/heads/develop" ]
          then
            dist_tag=$DIST_TAG_DEVELOP
          else
            echo "Unknown release branch ('$GITHUB_REF'), expected 'refs/heads/master' or 'refs/heads/develop'"
            exit 1
          fi

          published_version=$(npm view xrange@$dist_tag version)
          incoming_version$(node -pe "require('./package.json').version;")

          if [ $published_version = $incoming_version ]
          then
            echo "Cannot publish $published_version again; please, update version by running 'npm version <version>'"
            exit 1
          fi

      # finally
      - run: npm publish
