name: Publish xrange

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Test changes on ${{ matrix.os }}, and collect coverage
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest

    steps:
      - uses: actions/checkout@v3.5.2
      - uses: actions/setup-node@v3.6.0
        with:
          node-version: '18.x'

      - run: npm ci
      - run: npm run test:ci -- --coverage

      - name: Save coverage report (only for Ubuntu)
        if: matrix.os == 'ubuntu-latest'
        uses: actions/upload-artifact@v3.1.2
        with:
          name: xrange-coverage-at-${{ github.sha }}
          path: coverage

  publish:
    name: Build and publish
    runs-on: ubuntu-latest
    needs:
      - test

    steps:
      - uses: actions/checkout@v3.5.2
      - uses: actions/setup-node@v3.6.0
        with:
          node-version: '18.x'

      - run: npm ci

      - name: Publish
        run: |2
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_AUTH_TOKEN }}" > .npmrc

          npm publish --tag latest
