name: Test changes

on:
  push:
    branches-ignore:
      - main
      - 'skip-ci-tests/*'

jobs:
  unit:
    name: Run unit tests on ${{ matrix.os }} and collect coverage
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest

    steps:
      - uses: actions/checkout@v3.4.0
      - uses: actions/setup-node@v3.6.0
        with:
          node-version: '18.x'

      - run: npm ci
      - run: npm run build
      - run: npm run test:ci
