name: Test changes

on: push

jobs:
  unit:
    name: Run unit tests and collect coverage
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - run: npm ci
      - run: npm run build
      - run: npm run test:ci

      - if: failure()
        uses: actions/upload-artifact@v1
        with:
          name: xrange-unit-test-fail-log
          path: unit-test-fail.log

      - if: always()
        uses: actions/upload-artifact@v1
        with:
          name: xrange-coverage
          path: coverage
