name: Test changes

on:
  - push
  - pull_request

jobs:
  unit:
    name: Run unit tests on ${{ matrix.os }} and collect coverage
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macOS-latest

    steps:
      - uses: actions/checkout@v2

      - run: npm ci
      - run: npm run build
      - run: npm run test:ci

      - name: Save unit test fail log (skipped if no failures)
        if: failure()
        uses: actions/upload-artifact@v1
        with:
          name: xrange-unit-test-fail-log
          path: unit-test-fail.log

      # TODO: consider skipping the step more often
      - name: Save coverage report (only on pull requests)
        if: success() && github.event_name == 'pull_request'
        uses: actions/upload-artifact@v1
        with:
          name: xrange-coverage-at-${{ GITHUB_SHA }}
          path: coverage
